### ISSUE TITLE
Create templates for issues/PRs

### ISSUE THREAD

**Issue by jessefrench** [nss-evening-cohort-26/gitsub-your-worst-nightmare#2]
# User Story

# Acceptance Criteria

# Dependecies

# Dev Notes

**Comment by Zpcolburn** [comment]
# User Story


# Acceptance Criteria










# Dependecies


# Dev Notes

**Comment by Zpcolburn** [comment]
## Description


## Related Issue





## Motivation and Context


## How Can This Be Tested?


## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
